create table categories (id integer not null auto_increment, name varchar(255), primary key (id));
create table profile (id integer not null auto_increment, name varchar(255), primary key (id));
create table status (id integer not null auto_increment, name varchar(255), primary key (id));
create table tasks (id integer not null auto_increment, created_at datetime(6), description varchar(255), details varchar(255), due_date datetime(6), updated_at datetime(6), category_id integer not null, status_id integer not null, primary key (id));
create table users (username varchar(255) not null, created_at datetime(6), enabled bit, first_name varchar(255), last_name varchar(255), password varchar(255), updated_at datetime(6), primary key (username));
create table users_profiles (user_username varchar(255) not null, profiles_id integer not null);
alter table tasks add constraint FK19nbrmutuqhlidppwns1wmfro foreign key (category_id) references categories (id);
alter table tasks add constraint FKfmlm4rxoa19247blv9g96eacd foreign key (status_id) references status (id);
alter table users_profiles add constraint FKhpwjb3cislhdumt13joh9niq9 foreign key (profiles_id) references profile (id);
alter table users_profiles add constraint FK199o5h8t4br58h8solh5mvqp4 foreign key (user_username) references users (username);